name: Base workflow

on:
  workflow_dispatch:

jobs:
  send_repository_dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository_dispatch
        env:
          PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          curl \
            -X POST \
            -H "Authorization: token $PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/alalbux/github_actions/dispatches \
            -d '{"event_type":"base_built"}'
